### ISSUE TITLE
Releasing JS files

### ISSUE THREAD

**Issue by adrien-gthb** [AnteWall/angular2-emoji#2]
Hello,

I'm trying to use the angular2-emoji module in a project that is coded in plain javascript. It looks like in your module you only have released the typescript files. Could you please release the compiled typescript files?

Thank you!

**Comment by Dewep** [comment]
Hi,

I also use Angular 2 in ES5, I encounter the same worries. It would be cool to publish the JS files with the package.

Thanks.

**Comment by AnteWall** [comment]
Hi
The project i use this module on is currently put on hold, therefor i'm not currently developing it right now. If you want to download the code, build it and make a PR feel free and i will take the time to review it.

**Comment by harterc3** [comment]
I submitted a PR including the compiled js files in the repo. Up to @AnteWall whether he wants it in his project or not.
